# Generated by Django 4.2.24 on 2025-09-04 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("films_recommender_system", "0004_source_score_max"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="movie",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="review",
            name="author",
        ),
        migrations.RemoveField(
            model_name="review",
            name="score_max",
        ),
        migrations.RemoveField(
            model_name="source",
            name="base_url",
        ),
        migrations.RemoveField(
            model_name="source",
            name="credibility_level",
        ),
        migrations.RemoveField(
            model_name="source",
            name="score_max",
        ),
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(help_text="电影类型", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True,
                related_name="acted_movies",
                to="films_recommender_system.person",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="films_recommender_system.genre"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="language",
            field=models.CharField(default="en", max_length=20),
        ),
        migrations.AlterField(
            model_name="movie",
            name="length",
            field=models.IntegerField(blank=True, help_text="片长(分钟)", null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="original_title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="scriptwriters",
            field=models.ManyToManyField(
                blank=True,
                related_name="written_movies",
                to="films_recommender_system.person",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="movietitle",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="movietitle",
            name="language",
            field=models.CharField(default="zh-CN", max_length=10),
        ),
        migrations.AlterField(
            model_name="movietitle",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="titles",
                to="films_recommender_system.movie",
            ),
        ),
        migrations.AlterField(
            model_name="movietitle",
            name="title_text",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="films_recommender_system.movie",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="films_recommender_system.source",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(
                help_text="数据来源网站", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userreview",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="films_recommender_system.movie",
            ),
        ),
        migrations.AlterField(
            model_name="userreview",
            name="rating",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="userreview",
            name="review",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="movie",
            name="imdb_id",
        ),
    ]
